export enum ModalNames {
  COMPLETE_STREETS = 'COMPLETE_STREETS',
  ENV_JUSTICE = 'ENV_JUSTICE',
  TRANSIT_VEHICLES_ELECTRIC = 'TRANSIT_VEHICLES_ELECTRIC',
  MISSION_STATEMENT = 'MISSION_STATEMENT',
  CONTACT_US = 'CONTACT_US'
}
